app_config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("board.urls", namespace="board")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/urls.py
from django.urls import path

from board.views import (
    IndexListView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectUpdateView,
    ProjectDetailView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    TaskCreateView,
    WorkerProjectListView,
    WorkerTaskListView,
    WorkerCreateView,
    toggle_assign_to_task,
    toggle_task_change_is_completed,
)

app_name = "board"

urlpatterns = [
    path("", IndexListView.as_view(), name="index"),
    path(
        "projects/create/", ProjectCreateView.as_view(), name="project-create"
    ),
    path(
        "projects/user/<int:pk>/list/",
        WorkerProjectListView.as_view(),
        name="user-project-list",
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project-update",
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project-delete",
    ),
    path(
        "projects/<int:pk>/detail/",
        ProjectDetailView.as_view(),
        name="project-detail",
    ),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path(
        "tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"
    ),
    path(
        "tasks/user/<int:pk>/list/",
        WorkerTaskListView.as_view(),
        name="user-task-list",
    ),
    path(
        "tasks/<int:pk>/toogle_assign/",
        toggle_assign_to_task,
        name="task-toggle-assign",
    ),
    path(
        "tasks/<int:pk>/toogle_change_is_completed/",
        toggle_task_change_is_completed,
        name="task-change-is-completed",
    ),
    path("worker/create/", WorkerCreateView.as_view(), name="worker-create"),
]

templates/includes/footer.html
<footer class="fixed-bottom bg-dark text-white footer">
  <div class="container">
    <p>&copy; 2023 Task Board, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </div>
</footer>

templates/includes/navbar.html
{% load crispy_forms_filters %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Task Board</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url "board:index" %}">All projects</a>
      </li>
      {% if user.pk %}
        <li class="nav-item">
          <a class="nav-link" href="{% url "board:user-project-list" pk=user.pk %}">My projects</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "board:user-task-list" pk=user.pk %}">My tasks</a>
        </li>
      {% endif %}
    </ul>
    {% if user.pk %}
      <a class="btn btn-outline-light mx-2" href="{% url "board:project-create" %}">
        Create project
      </a>
      <a class="btn btn-outline-light mx-2" href="{% url "board:task-create" %}">
        Create task
      </a>
    {% endif %}


    <ul class="navbar-nav ml-auto">

      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="#">{{ user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "logout" %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url "login" %}">Login</a>
      </li>
      {% endif %}
    </ul>
    <form method="get" class="form-inline">
      {{ search_form|crispy}}
      <button class="btn btn-outline-light mx-2 " type="submit">Search</button>
    </form>
  </div>
</nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination justify-content-center mt-5">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number%}">
          prev
        </a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item card-link" style="color: #212529">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<div class="col-md-3 sidebar">
  <div class="project-info">
    <h4>Statistic</h4>
    <h5>Tasks:</h5>
    <ul class="form-check-label">
      <li>total number - {{ tasks_total_number }}</li>
      <li>done - {{ tasks_done }}</li>
      <li>in process - {{ tasks_in_proces }} </li>
      <li>expired - {{ tasks_expired }}</li>
    </ul>
    <h5>Staff:</h5>
    <ul class="form-check-label">
      <li>total number - {{ staff }}</li>
    </ul>
  </div>

  <h5 >Filters</h5>
  <form method="get">
    {{ filter_form.as_p }}
    <button type="submit" class="btn comment-btn">Submit</button>
  </form>
</div>