app_config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("board.urls", namespace="board")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/urls.py
from django.urls import path

from board.views import (
    IndexListView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectUpdateView,
    ProjectDetailView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    TaskCreateView,
    WorkerProjectListView,
    WorkerTaskListView,
    WorkerCreateView,
    toggle_assign_to_task,
    toggle_task_change_is_completed,
)

app_name = "board"

urlpatterns = [
    path("", IndexListView.as_view(), name="index"),
    path(
        "projects/create/", ProjectCreateView.as_view(), name="project-create"
    ),
    path(
        "projects/user/<int:pk>/list/",
        WorkerProjectListView.as_view(),
        name="user-project-list",
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project-update",
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project-delete",
    ),
    path(
        "projects/<int:pk>/detail/",
        ProjectDetailView.as_view(),
        name="project-detail",
    ),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path(
        "tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"
    ),
    path(
        "tasks/user/<int:pk>/list/",
        WorkerTaskListView.as_view(),
        name="user-task-list",
    ),
    path(
        "tasks/<int:pk>/toogle_assign/",
        toggle_assign_to_task,
        name="task-toggle-assign",
    ),
    path(
        "tasks/<int:pk>/toogle_change_is_completed/",
        toggle_task_change_is_completed,
        name="task-change-is-completed",
    ),
    path("worker/create/", WorkerCreateView.as_view(), name="worker-create"),
]

board/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class Position(models.Model):
    name = models.CharField(max_length=63, unique=True, default="Developer")

    def __str__(self) -> str:
        return self.name


class TaskType(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self) -> str:
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        on_delete=models.SET_NULL,
        null=True,
        related_name="workers",
    )

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}" f"({self.position.name})"


class Task(models.Model):
    TASK_PRIORITY = [
        ("urgent", "Urgent"),
        ("high", "High"),
        ("medium", "Medium"),
        ("low", "Low"),
    ]

    MEDIUM_PRIORITY = TASK_PRIORITY[2][0]

    name = models.CharField(max_length=63)
    description = models.TextField(blank=True, null=True)
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(
        max_length=15, choices=TASK_PRIORITY, default=MEDIUM_PRIORITY
    )
    task_type = models.ForeignKey(
        TaskType,
        on_delete=models.CASCADE,
    )
    assignees = models.ManyToManyField(settings.AUTH_USER_MODEL)

    project = models.ForeignKey(
        "Project", on_delete=models.CASCADE, related_name="tasks"
    )

    class Meta:
        default_related_name = "tasks"

    def __str__(self) -> str:
        return self.name


class Project(models.Model):
    PROJECT_STATUS = [
        (1, "In development"),
        (2, "In support"),
        (3, "Deployed"),
        (4, "Closed"),
    ]

    name = models.CharField(max_length=63)
    description = models.TextField()
    deadline = models.DateTimeField()
    status = models.IntegerField(choices=PROJECT_STATUS, default=1)

    def __str__(self) -> str:
        return self.name

board/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404
from django.utils import timezone

from board.models import Project, Task


class WorkerCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
            "position",
        )


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = "__all__"
        widgets = {
            "deadline": forms.DateInput(attrs={"type": "date"})
        }

    def clean_deadline(self):
        deadline = self.cleaned_data.get("deadline")
        if deadline < timezone.now():
            raise forms.ValidationError("Deadline must be in the future.")
        return deadline


class TaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "deadline": forms.DateInput(attrs={"type": "date"}),
            "description": forms.Textarea(attrs={"style": "width: 100%"})
        }

    def clean_deadline(self):
        deadline = self.cleaned_data.get("deadline")
        project = get_object_or_404(Project, pk=self.data.get("project"))
        if deadline < timezone.now():
            raise forms.ValidationError("Deadline must be in the future.")
        if deadline > project.deadline:
            raise forms.ValidationError(
                "Task deadline must not be farther then project's deadline."
            )
        return deadline


class SearchForm(forms.Form):
    search_criteria = forms.CharField(
        max_length=63,
        label="",
        show_hidden_initial="Search...",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
        required=False,
    )


class FilterForm(forms.Form):
    DEADLINE_SORTING = [("deadline", "ascending"), ("-deadline", "descending")]

    status = forms.MultipleChoiceField(
        choices=Project.PROJECT_STATUS,
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    deadline = forms.ChoiceField(
        choices=DEADLINE_SORTING,
        widget=forms.RadioSelect,
    )

board/views.py
from datetime import date

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from board.forms import TaskForm, ProjectForm, WorkerCreationForm, SearchForm
from board.models import Task, Project, Worker
from board.mixins import (
    SearchFormQuerySetMixin,
    FilterFormMixin,
    SearchFormContextMixin,
)


class IndexListView(
    SearchFormContextMixin,
    SearchFormQuerySetMixin,
    FilterFormMixin,
    generic.ListView,
):
    model = Project
    template_name = "board/index.html"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tasks_info = Task.objects.all()
        staff = Worker.objects.all()
        context["tasks_total_number"] = tasks_info.count()
        context["tasks_in_proces"] = tasks_info.filter(
            is_completed=False
        ).count()
        context["tasks_done"] = tasks_info.filter(is_completed=True).count()
        context["tasks_expired"] = tasks_info.filter(
            deadline__lt=date.today(), is_completed=False
        ).count()
        context["staff"] = staff.count()

        return context


class WorkerProjectListView(
    LoginRequiredMixin,
    SearchFormQuerySetMixin,
    SearchFormContextMixin,
    FilterFormMixin,
    generic.ListView,
):
    model = Project
    template_name = "board/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        worker = get_user_model().objects.get(pk=self.request.user.pk)
        assigned_tasks = worker.tasks.all()

        staff = set()
        for task in assigned_tasks:
            staff.update(task.assignees.all())

        context["tasks_total_number"] = assigned_tasks.count()
        context["tasks_in_proces"] = assigned_tasks.filter(
            is_completed=False
        ).count()
        context["tasks_done"] = assigned_tasks.filter(
            is_completed=True
        ).count()
        context["tasks_expired"] = assigned_tasks.filter(
            deadline__lt=date.today(), is_completed=False
        ).count()
        context["staff"] = len(staff)

        return context

    def get_queryset(self):
        user_pk = self.kwargs.get("pk")
        queryset = (
            super().get_queryset().filter(tasks__assignees=user_pk).distinct()
        )
        return queryset


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy("board:index")


class ProjectDetailView(
    LoginRequiredMixin, SearchFormContextMixin, generic.DetailView
):
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tasks_info = kwargs.get("object").tasks.all()
        staff = Worker.objects.filter(tasks__project=self.object).distinct()
        context["tasks_total_number"] = tasks_info.count()
        context["tasks_in_proces"] = tasks_info.filter(
            is_completed=False
        ).count()
        context["tasks_done"] = tasks_info.filter(is_completed=True).count()
        context["tasks_expired"] = tasks_info.filter(
            deadline__lt=date.today(), is_completed=False
        ).count()
        context["staff"] = staff.count()
        search_form = SearchForm(self.request.GET)

        if search_form.is_valid():
            context["task_list"] = self.object.tasks.filter(
                name__icontains=search_form.cleaned_data["search_criteria"]
            )

        return context


class ProjectUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy("board:index")


class ProjectDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Project
    success_url = reverse_lazy("board:index")
    template_name = "board/confirm_delete.html"


class WorkerCreateView(generic.CreateView):
    model = get_user_model()
    form_class = WorkerCreationForm
    template_name = "registration/sign-up.html"
    success_url = reverse_lazy("login")


class WorkerTaskListView(
    LoginRequiredMixin,
    SearchFormContextMixin,
    SearchFormQuerySetMixin,
    generic.ListView,
):
    model = Task
    template_name = "board/task_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        worker = get_user_model().objects.get(pk=self.request.user.pk)
        assigned_tasks = worker.tasks.all()

        staff = set()
        for task in assigned_tasks:
            staff.update(task.assignees.all())

        context["tasks_total_number"] = assigned_tasks.count()
        context["tasks_in_proces"] = assigned_tasks.filter(
            is_completed=False
        ).count()
        context["tasks_done"] = assigned_tasks.filter(
            is_completed=True
        ).count()
        context["tasks_expired"] = assigned_tasks.filter(
            deadline__lt=date.today(), is_completed=False
        ).count()
        context["staff"] = len(staff)

        return context

    def get_queryset(self):
        user_pk = self.kwargs.get("pk")
        queryset = super().get_queryset().filter(assignees=user_pk)
        return queryset


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("board:index")


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    queryset = Task.objects.prefetch_related("assignees")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("board:index")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    template_name = "board/confirm_delete.html"
    success_url = reverse_lazy("board:index")


@login_required
def toggle_assign_to_task(request, pk):
    worker = get_user_model().objects.get(pk=request.user.id)
    if (
        Task.objects.get(pk=pk) in worker.tasks.all()
    ):  # probably could check if car exists
        worker.tasks.remove(pk)
    else:
        worker.tasks.add(pk)
    return HttpResponseRedirect(reverse_lazy("board:task-detail", args=[pk]))


@login_required
def toggle_task_change_is_completed(request, pk):
    task = Task.objects.get(pk=pk)
    if task.is_completed:
        task.is_completed = False
    else:
        task.is_completed = True
    task.save()
    return HttpResponseRedirect(reverse_lazy("board:task-detail", args=[pk]))

templates/board/confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <h1>Delete Project?</h1>
    <form method="post">
      {% csrf_token %}

      <div>
        <input type="submit" value="Yes" class="btn comment-btn">
        <a href="{{ request.GET.previously }}">
          <button class="btn comment-btn">
            Cancel
          </button>
        </a>
      </div>
    </form>
  </div>
{% endblock %}

templates/board/index.html
{% extends "base.html" %}

{% block sidebar %}
  {% include "includes/sidebar.html" %}
{% endblock %}

{% block content %}
  <div class="col-md-9">
    <main role="main" class="container-fluid">
    <div>
      <h1 class="mt-5">Welcome to the task board</h1>
      <h4>Here is list of all projects</h4>
    </div>
      <div class="row row-cols-5">
        {% for project in project_list %}
          <div class="col-sm-3">
            <!-- Project Card 1 -->
            <a class="card-link" href="{% url "board:project-detail" pk=project.pk %}">
              <div class="card">
                <div class="card-header text-white" style="background-color:
                    {% if project.status == 1 %}
                      #00ff99
                    {% elif project.status == 2 %}
                      #99ccff
                    {% elif project.status == 3 %}
                      #ffcc99
                    {% else %}
                      #ff6666
                    {% endif %}">
                  {{ project.name }}
                </div>
                <div class="card-body">
                  <p class="card-text overflow-auto" style="max-height: 100px;">
                    {{ project.description }}
                  </p>
                </div>
                <div class="card-footer">
                  Deadline: {{ project.deadline|date:"Y-m-d" }}
                </div>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
      <!-- Pagination -->
      {% include "includes/pagination.html" %}
    </main>
  </div>
{% endblock %}}

templates/board/project_detail.html
{% extends "base.html" %}

{% block sidebar %}
  {% include "includes/sidebar.html" %}
{% endblock %}

{% block content %}
  <div class="col-md-9">
    <main role="main" class="container-fluid">
      <div>
        <h1 class="mt-5" style="display: inline-block">
          {{ project.name }}
          <a class="btn comment-btn" href="{% url "board:project-update" pk=project.pk %}">
            Update
          </a>
          <a class="btn comment-btn" href="{% url "board:project-delete" pk=project.pk %}">
            Delete
          </a>
        </h1>
      </div>
      <p class="lead">{{ project.description }}</p>
      {% if project.tasks.all %}
        <div class="row row-cols-5">
          {% for task in task_list %}
            <div class="col-sm-3">
              <!-- Project Card 1 -->
              <a class="card-link" href="{% url "board:task-detail" pk=task.pk %}">
                <div class="card">
                  <div class="card-header text-white" style="background-color:
                    {% if task.priority == "low" %}
                      #ccff99
                    {% elif task.priority == "medium" %}
                      #ffcc99
                    {% elif task.priority == "high" %}
                      #ff9933
                    {% else %}
                      #ff8080
                    {% endif %}">
                    {{ task.name }}
                  </div>
                  <div class="card-body">
                    <p class="card-text overflow-auto" style="max-height: 100px;">
                      {{ task.description }}
                    </p>
                  </div>
                  <div class="card-footer">
                    Deadline: {{ task.deadline|date:"Y-m-d" }}
                  </div>
                </div>
              </a>
            </div>
          {% endfor %}
      </div>
      {% else %}
        <p>The project has not any tasks yet</p>
      {% endif %}
      <!-- Pagination -->
      {% include "includes/pagination.html" %}
    </main>
  </div>
{% endblock %}

templates/board/project_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <div class="col-md-11">
      <div class="row detail-box">
        <div class="col-5 task-detail">
          <h1>{{ object|yesno:"Update,Create" }} Project </h1>
          <form method="post" action="">
            {% csrf_token %}
            {{ form.as_p}}
            <button class="btn btn-outline-light mx-2" type="submit">Create project</button>
            <button class="btn btn-outline-light mx-2" type="submit">Cancel</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/board/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <h1>Delete task?</h1>
    <form method="post">
      {% csrf_token %}

      <div>
        <input type="submit" value="Yes" class="btn btn-danger">
        <a href="{{ request.GET.previously }}">
          <button class="btn btn-secondary">
            Cancel
          </button>
        </a>
      </div>
    </form>
  </div>
{% endblock %}

templates/board/task_detail.html
{% extends "base.html" %}


{% block content %}
  <div class="col-md-11">
    <div class="row detail-box">
      <div class="col-5 task-detail">
        <div>
          <div style="margin-bottom: 30px">
            <a class="btn btn-outline-light mx-2" href="{% url "board:task-update" task.pk%}">
              Update task
            </a>
            <a class="btn btn-outline-light mx-2" href="{% url "board:task-delete" task.pk%}">
              Delete task
            </a>
            <span class="task-status float-right">
              priority: {{ task.priority }} | status: {{ task.is_completed|yesno:"done,in process" }} | deadline: {{ task.deadline|date:"Y-m-d" }}
            </span>
          </div>
        </div>
        <h3 class="task-name" style="display: inline-block">{{ task.name }}</h3>
        <div class="float-right">
            <a class="btn btn-outline-light mx-2" href="{% url "board:task-change-is-completed" task.pk%}">
              {{ task.is_completed|yesno:"Open,Close" }} task
            </a>
        </div>
        <p class="task-description">
          {{ task.description }}
        </p>
        <h5> Assigned to:</h5>
        {% if task.assignees.all %}
        <table class="table table-striped table-dark table-wrapper-scroll-y" >
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Username</th>
              <th scope="col">Position</th>
              <th scope="col">Email</th>
            </tr>
          </thead>
            {% for worker in task.assignees.all %}
              <tbody>
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{worker.username}}</td>
                <td>{{ worker.position }}</td>
                <td>{{ worker.email }}</td>
              </tr>
              </tbody>
            {% endfor %}
        </table>
        {% else %}
          <p>This task has been assigned to anyone yet</p>
        {% endif %}
        <form method="post" action="{% url "board:task-toggle-assign" pk=task.pk %}" class="form-inline">
          {% csrf_token %}
          {% if user in task.assignees.all %}
            <button class="btn btn-outline-light mx-2" type="submit">Delete me</button>
          {% else %}
            <button class="btn btn-outline-light mx-2" type="submit">Assign me</button>
          {% endif %}
        </form>
      </div>
      <div class="col-6 comments">
        <div class="col-6 comments">
          <div class="panel">
            <div class="panel-body">
              <div class="media-block">
                <div class="media-body">
                  <div class="mar-btm">
                    <a href="#" class="btn-link text-semibold media-heading box-inline">Lisa D.</a>
                  </div>
                  <p>consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
                  <div class="pad-ver">
                    <div class="btn-group">
                      <a class="btn btn-sm btn-default btn-hover-success" href="#"><i class="fa fa-thumbs-up"></i></a>
                      <a class="btn btn-sm btn-default btn-hover-danger" href="#"><i class="fa fa-thumbs-down"></i></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="media-block">
                <div class="media-body">
                  <div class="mar-btm">
                    <a href="#" class="btn-link text-semibold media-heading box-inline">Lisa D.</a>
                  </div>
                  <p>consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
                  <div class="pad-ver">
                    <div class="btn-group">
                      <a class="btn btn-sm btn-default btn-hover-success" href="#"><i class="fa fa-thumbs-up"></i></a>
                      <a class="btn btn-sm btn-default btn-hover-danger" href="#"><i class="fa fa-thumbs-down"></i></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="media-block">
                <div class="media-body">
                  <div class="mar-btm">
                    <a href="#" class="btn-link text-semibold media-heading box-inline">Lisa D.</a>
                  </div>
                  <p>consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
                  <div class="pad-ver">
                    <div class="btn-group">
                      <a class="btn btn-sm btn-default btn-hover-success" href="#"><i class="fa fa-thumbs-up"></i></a>
                      <a class="btn btn-sm btn-default btn-hover-danger" href="#"><i class="fa fa-thumbs-down"></i></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="media-block">
                <div class="media-body">
                  <div class="mar-btm">
                    <a href="#" class="btn-link text-semibold media-heading box-inline">Lisa D.</a>
                  </div>
                  <p>consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
                  <div class="pad-ver">
                    <div class="btn-group">
                      <a class="btn btn-sm btn-default btn-hover-success" href="#"><i class="fa fa-thumbs-up"></i></a>
                      <a class="btn btn-sm btn-default btn-hover-danger" href="#"><i class="fa fa-thumbs-down"></i></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="media-block">
                <div class="media-body">
                  <div class="mar-btm">
                    <a href="#" class="btn-link text-semibold media-heading box-inline">Lisa D.</a>
                  </div>
                  <p>consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
                  <div class="pad-ver">
                    <div class="btn-group">
                      <a class="btn btn-sm btn-default btn-hover-success" href="#"><i class="fa fa-thumbs-up"></i></a>
                      <a class="btn btn-sm btn-default btn-hover-danger" href="#"><i class="fa fa-thumbs-down"></i></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="media-block">
                <div class="media-body">
                  <div class="mar-btm">
                    <a href="#" class="btn-link text-semibold media-heading box-inline">Lisa D.</a>
                  </div>
                  <p>consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
                  <div class="pad-ver">
                    <div class="btn-group">
                      <a class="btn btn-sm btn-default btn-hover-success" href="#"><i class="fa fa-thumbs-up"></i></a>
                      <a class="btn btn-sm btn-default btn-hover-danger" href="#"><i class="fa fa-thumbs-down"></i></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <form>
            <div class="form-group comment-form">
              <textarea class="form-control" id="comment" rows="3"></textarea>
            </div>
            <button type="submit" class="btn comment-btn">Comment</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/board/task_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="col-md-11">
      <div class="row detail-box">
        <div class="col-10 task-detail">
          <h1>{{ object|yesno:"Update,Create" }} Task</h1>
          <form method="post" action="">
            {% csrf_token %}
            <table class="table table-striped table-dark table-wrapper-scroll-y" >
              <thead>
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">Task type</th>
                  <th scope="col">Project</th>
                  <th scope="col">Priority</th>
                  <th scope="col">Deadline</th>
                  <th scope="col">Completed</th>
                </tr>
              </thead>
                <tbody>
                  <tr>
                    <td>{{ form.name }}</td>
                    <td>{{ form.task_type }}</td>
                    <td>{{ form.project }}</td>
                    <td>{{ form.priority }}</td>
                    <td>{{ form.deadline }}</td>
                    <td>{{ form.is_completed }}</td>
                  </tr>
                </tbody>
            </table>
            <div>
              {{ form.description }}
            </div>
            <div class="container">
              <div class="row row-cols-3">
                {% for worker in form.assignees %}
                  <div class="col">{{ worker }}</div>
                {% endfor %}
              </div>
            </div>
            <button class="btn btn-outline-light mx-2" type="submit">{{ object|yesno:"Update,Create" }} task</button>
            <a class="btn btn-outline-light mx-2" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/board/task_list.html
{% extends "base.html" %}

{% block sidebar %}
  {% include "includes/sidebar.html" %}
{% endblock %}

{% block content %}
    <div class="col-md-9">
    <main role="main" class="container-fluid">
      <h1 class="mt-5">{{ user.username }} tasks list:</h1>
      <div class="row row-cols-5">
        {% for task in task_list %}
          <div class="col-sm-3">
            <!-- Project Card 1 -->
            <a class="card-link" href="{% url "board:task-detail" pk=task.pk %}">
              <div class="card">
                <div class="card-header text-white" style="background-color:
                    {% if task.priority == "low" %}
                      #ccff99
                    {% elif task.priority == "medium" %}
                      #ffcc99
                    {% elif task.priority == "high" %}
                      #ff9933
                    {% else %}
                      #ff8080
                    {% endif %}">
                  {{ task.name }}
                </div>
                <div class="card-body">
                  <p class="card-text overflow-auto" style="max-height: 100px;">
                    {{ task.description }}
                  </p>
                </div>
                <div class="card-footer">
                  Deadline: {{ task.deadline|date:"Y-m-d" }}
                </div>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
      <!-- Pagination -->
      {% include "includes/pagination.html" %}
    </main>
  </div>
{% endblock %}